name: Deploy Edge Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/backend/supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: mkbyoxzrcbtplxmxhpce

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          cd packages/backend
          supabase link --project-ref $PROJECT_ID
          supabase functions deploy sync-congress --project-ref $PROJECT_ID 